name: PII Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Allows the workflow to read and write repository contents

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: |
        echo "Listing contents of the workspace"
        ls -al
        echo "Checking Git status"
        git status

    - name: Run Trufflehog
      run: |
        git init
        git remote add origin https://github.com/your-repo.git
        git fetch origin
        git checkout your-branch
        trufflehog --json > results.json || echo "Trufflehog failed"
    - name: Display results
      run: cat results.json || echo "No results"

    - name: Print results
      if: always()
      run: cat results.json
