name: PII Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight
  push:
    branches:
      - main

jobs:

  pii-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Scan for PII
      uses: trufflesecurity/trufflehog@v3.2.0
      with:
        scanArguments: "--regex --rules=pii-rules.json"
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: trufflehog-results
        path: trufflehog_results.json
