name: PII Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@v3.2.0
      with:
        entryPoint: 'trufflehog'  # Correct input instead of 'scanArguments'
        args: '--json --json=true'
