name: PII Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write  # Allows the workflow to read and write repository contents

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files for debugging
      run: |
        echo "Listing contents of the workspace"
        ls -al
        echo "Checking Git status"
        git status

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@v3.2.0
      with:
        entryPoint: 'trufflehog'
        args: 'filesystem --directory . --rules-file pii-rules.json --json --jsonfile results.json'

    - name: Print results
      if: always()
      run: cat results.json
